// Reseñas reales extraídas del sitio original (pitcharge.com), agrupadas por
// slug de juego. Sirven de contenido inicial de prueba social — la sección de
// reseñas es clave para conversión y SEO en cada página de producto.

export interface ProductReview {
  author: string;
  content: string;
  rating: number;
  date: string;
}

export const reviewsBySlug: Record<string, ProductReview[]> = {
  "free-fire": [
    { author: "Alexis", content: "Excelente servicio, muy confiable, muchas gracias Pitanga por sus servicios", rating: 5, date: "2025-09-17" },
    { author: "Andrés Morillo", content: "10/10 amo esta página la mejor y la más confiable súper recomendada", rating: 5, date: "2026-02-22" },
    { author: "Jhoneiber lopez", content: "Exelente servicio con buena atención al cliente y exelente página", rating: 4, date: "2026-05-24" },
    { author: "danielitovegas2000", content: "Ecxelente aplicación facilita la recarga muy buena 👏🏾", rating: 5, date: "2025-07-27" },
    { author: "Jose", content: "Muy buen servicio son puntuales y de mucha confianza", rating: 5, date: "2026-02-14" },
    { author: "Matheus Montoya", content: "Excelente servicio muy bueno la verdad lo mejores", rating: 5, date: "2026-05-14" },
    { author: "Carolina", content: "Es facil el procedimiento y además llega rapido", rating: 5, date: "2025-09-08" },
    { author: "Juan gerratana", content: "Excelente la recarga me llego inmediato", rating: 5, date: "2025-05-29" },
    { author: "Denyer", content: "Es muy fiable me gustó el servicio", rating: 5, date: "2025-09-13" },
    { author: "Virginia gonzalez", content: "excelentes, rápidos y confiables", rating: 5, date: "2026-05-11" },
    { author: "naspe.leidys", content: "Excelente .. estoy satisfecha", rating: 5, date: "2025-08-13" },
    { author: "Jose", content: "Recomendado al 100 porciento", rating: 4, date: "2026-01-17" },
    { author: "Jose", content: "Recomendado super comfiables", rating: 5, date: "2026-01-17" },
    { author: "Carlos", content: "Muy bueno excelente servicio", rating: 5, date: "2026-04-30" },
    { author: "Jorge", content: "Es una web muy confiable", rating: 5, date: "2025-08-29" },
    { author: "cmaestre1711", content: "Muy rápido y confiable 😃", rating: 5, date: "2026-04-20" },
    { author: "Maykel", content: "Muy bueno excelente", rating: 5, date: "2026-05-11" },
    { author: "endryck vásquez", content: "muy confiable 100%", rating: 5, date: "2025-09-14" },
  ],
  "call-of-duty-mobile": [
    { author: "Fabrizio Peralta", content: "Quiero expresar mi más sincero agradecimiento por el excelente servicio que recibí. Desde el primer momento, me sentí valorado como cliente, y la atención al detalle fue excepcional. Su equipo no solo demostró un profundo conocimiento de sus productos, sino que también brindó un ambiente de confianza y calidez que hizo que mi experiencia fuera memorable. Sin duda, recomendaré sus servicios a amigos y familiares. ¡Gracias por hacerme sentir tan bienvenido", rating: 5, date: "2026-06-02" },
    { author: "Carlos", content: "La mejor opción que puedes usar para recargar  tus juegos de tantas que he usado es la mejor de todas fácil rápido y confiable no lo creí pero es verdad muchas gracias a la comunidad de esta página por la sugerencia mi centro de recargar número 1!♥️", rating: 5, date: "2026-02-20" },
    { author: "yerson.soto23", content: "No suelo hacer reseñas xq en muchas ocasiones me han quedo mal ....  Pero en esta ocasión   Me dejan sin palabras   Muy buena la atención rápido y confiable   Ya encontré el lugar indicado para recargar mis cps .  Gracias por tan buena atención", rating: 5, date: "2025-07-13" },
    { author: "Yeferson castillo", content: "Exelente servicio no se demoraron máximo 10 minutos en realizarla súper confiables . Si tienen alguna duda ellos les responderan  inmediato .me gustó el respeto q tienen con la información gracias", rating: 5, date: "2025-09-20" },
    { author: "Pablo", content: "Excelente servicio lo recomiendo al 100% seguro y confiable te atienden rápido con solo con seguir los pasos de su página oficial tendrás tú recarga de CP lo recomiendo", rating: 5, date: "2025-11-09" },
    { author: "kerwinpaz17", content: "Primera compra que hago por la página desde que está en funcionamiento y es una BELLEZA PURA... RÁPIDO, SEGURO Y LO MEJOR RESPONSABLES, les recomiendo que la prueben", rating: 5, date: "2025-09-05" },
    { author: "Carlos (Guayo)", content: "LE DOY PUNTUACIÓN MAXIMA PORQUE DE VERDAD QUE ES RAPIDO, SON MUY RESPONSABLES EN MENOS DE 5 MNTS DESPUES DE REALIZAR MI PAGO ME REALIZARON LA RECARGA.", rating: 5, date: "2025-11-06" },
    { author: "Miguel", content: "Excelente página de servicio para recargas de verdad se las recomiendo eficiencia al responder y rapidez a recargar los Cp se los recomiendo", rating: 5, date: "2025-06-20" },
    { author: "Robert", content: "Sinceramente muchas gracias por si atención y sobre todo la seriedad es mi primera vez y se verdad q serán los favoritos pra mis recargas 🫡", rating: 5, date: "2026-02-13" },
    { author: "Ronald Ramirez", content: "Muy buena aplicación recomendada al 99999999% en menos de 5min estaba listo cosa que no hacen los demás, de mi parte muy buena 🙏", rating: 5, date: "2025-07-29" },
    { author: "Wilson", content: "Excelente servicio, me estrese por no haber leído el tiempo de recarga, pero la verdad rápido y confiable, gracias y disculpen❤️", rating: 5, date: "2025-09-06" },
    { author: "Jesus", content: "Es un gran método de recarga de cod point me gusta por qué hacen las recargas a tiempo y le doy 5 estrellas por si gran servicio", rating: 5, date: "2026-04-16" },
    { author: "Robert", content: "Son la mejor opción, rápido, sencillo y muy seguro. En menos de 10 minutos obtuve mis CP👌🏽 mejor página, se las recomiendo.", rating: 5, date: "2025-07-02" },
    { author: "William Urdaneta", content: "La verdad es una app súper confiable y eficiente es muy fácil de usar y en menos de 20 minutos ya está hecho la recarga", rating: 5, date: "2025-12-03" },
    { author: "figueredofelixf", content: "Excelente y muy rápido el proceso... Muy buena atención y explicación de como hacer su recarga... Lo recomiendo 10000%", rating: 5, date: "2026-01-15" },
    { author: "Mario", content: "La verdad al principio si dude y estaba exeptico, sin embargo confie y todo salio a la perfeccion, 10/10 nuevo cliente", rating: 5, date: "2026-06-13" },
    { author: "Daniel", content: "Primera vez que recargo, fue fácil, rápido, con excelente atención y super confiables, los recomiendo totalmente", rating: 5, date: "2025-07-01" },
    { author: "diosme romero", content: "Muy confiable para recargar no ay estafa ni problema, más bien te ayuda a corregir errores si tienen un problema", rating: 5, date: "2026-02-19" },
  ],
  "blood-strike": [
    { author: "Natanael Martinez", content: "Muy rapido, bastante eficiente sin ninguna duda Recargaria por aqui siempre Buen servicio Muchas gracias u.u", rating: 5, date: "2025-11-28" },
    { author: "Adonis", content: "excelente página, la verdad es confiable, atención directa, rápida y segura, la recomiendo muchísimo", rating: 5, date: "2025-09-02" },
    { author: "Brayan", content: "Se las recomiendo la mejor página para comprar 100 % seguro y las recargas te llegan rápido", rating: 5, date: "2025-07-04" },
    { author: "Miguel Jiménez", content: "Supere recomendable y una atención al cliente inmediata, se más recomiendo", rating: 5, date: "2025-07-11" },
    { author: "Yefren Lopez", content: "Buena muy buena experiencia atentos al servicio rápidos y confiables", rating: 5, date: "2026-04-01" },
    { author: "Yoiber", content: "Es demasiado buena y confiables y las recargas son de inmediato", rating: 5, date: "2025-10-29" },
    { author: "Olenkys", content: "Excelente muy seguro y rápido el método de recarga recomendado", rating: 5, date: "2025-11-15" },
    { author: "Daniel Rios", content: "Muy buena pagina para recagar 10 de 10 super rapida y atentos.", rating: 5, date: "2026-06-08" },
    { author: "Justin Rosario", content: "Me parece super eficiente y a la vez eficaz muy buen servicio", rating: 5, date: "2025-08-01" },
    { author: "Jesús", content: "Super recomendado, seguro y eficiente que más puedo pedir", rating: 5, date: "2025-07-05" },
    { author: "Gabriel Bermudez", content: "Se la recomiendo al 100%100 confiable es la mejor que hay", rating: 5, date: "2026-02-17" },
    { author: "Pablo", content: "Lo mejor en recargas efectiva y rápidas la recomiendo", rating: 5, date: "2025-11-02" },
    { author: "Juan Morán", content: "Buen servicio y rápido, no lo dudes, es 100% seguro", rating: 5, date: "2025-10-21" },
    { author: "Yender", content: "Muy buena página de recarga recomendada 100% segura", rating: 5, date: "2026-01-31" },
    { author: "Sabniel Contreras", content: "Es rápido y efectivo 100% recomendado", rating: 5, date: "2025-08-18" },
    { author: "Julio cesar Sánchez", content: "Es buena tarda un poco paro si cumple", rating: 5, date: "2025-10-30" },
    { author: "YoanderJimenez", content: "Excelente servicio, recomendable 😉", rating: 5, date: "2025-08-06" },
    { author: "Jesús Tovar", content: "Es muy buena pagina", rating: 5, date: "2025-10-11" },
  ],
  "delta-force": [
    { author: "Karhu", content: "Fácil, rápido y con atención inmediata, es la primera vez que pruebo una página de recargas pero esta la recomiendo totalmente.", rating: 5, date: "2025-09-18" },
    { author: "Keniber", content: "Recarga rápidas y seguras con increíble atención al cliente", rating: 5, date: "2025-08-15" },
    { author: "Heyber", content: "Increíble servicio en menos de 10 minutos ya lo tenía", rating: 5, date: "2026-03-15" },
    { author: "hebertcamejo002", content: "Excelente servicio 👍", rating: 5, date: "2025-07-12" },
  ],
  "fc-mobile": [
    { author: "Bryant", content: "Demasiado buena esta página la verdad pense que me iban a estafar como las otras paginas pero me llego de una vez la recarga son super profesionales", rating: 5, date: "2026-06-01" },
    { author: "Jeyko", content: "es excelente, confiable y está abierto la mayoría del tiempo yo lo recomiendo y bueno malo es que si tarda un poco", rating: 5, date: "2026-03-22" },
    { author: "Johan", content: "Sin duda rapido y confiables la mejor pag que e visto muy conforme con sus precios y sus recargas rapidas", rating: 5, date: "2026-05-17" },
    { author: "Cristian mejías", content: "De verdad buen sitio de recargas, gente muy amable y puntual, se volvió mi sitio de recargas favoritao", rating: 5, date: "2026-02-18" },
    { author: "Fabio campos", content: "Exelente servicio al cliente responden rápido y la recarga está lista en menos de 10 min", rating: 5, date: "2025-08-09" },
    { author: "antonixxtrejo7", content: "Execelente servicio 100% confiables y buena atención los mejores para recargar", rating: 5, date: "2025-07-18" },
    { author: "antonixxtrejo7", content: "Excelente servicio 100% confiables y buenas atención los mejores para recargar", rating: 5, date: "2025-07-18" },
    { author: "Dylan", content: "Wow sorprendido demasiado rápido para una recarga y muy confiable recomendable", rating: 5, date: "2026-07-01" },
    { author: "Johandry", content: "Excelente servidor 100%confiable proceso rápido y fácil se los recomiendo", rating: 5, date: "2025-09-08" },
    { author: "javielitourdaneta056", content: "Saludos a todos los trabajadores de esta plataforma por un buen servicio", rating: 4, date: "2025-12-23" },
    { author: "isaacestabarojas", content: "Excelente servicio, rápido, fácil y confiable. Vale totalmente la pena", rating: 5, date: "2025-10-13" },
    { author: "cristian", content: "Muy buena experiencia y muy rápidos para hacer el correspondiente pago", rating: 5, date: "2025-11-09" },
    { author: "Richard guiza", content: "Muy bien servicio no tardan nada en hacerle la recarga muchas gracias", rating: 5, date: "2026-07-27" },
    { author: "wiljbermudezb", content: "100% garantizado, buen servicio, gran atención y sobre todo seguro", rating: 5, date: "2025-09-13" },
    { author: "Leonardo", content: "Excelentes en su trabajo, 100% confiables y excelente servicio", rating: 5, date: "2026-07-08" },
    { author: "Alejandro", content: "La verdad me atendieron super bien, fue rápido y confiable", rating: 5, date: "2026-05-17" },
    { author: "Camilo", content: "Buen servicio y confiable deverdad son los mejores 👍👍", rating: 5, date: "2025-10-28" },
    { author: "Moises Arcaya", content: "Muy buen servicio y rápidos al atender , 100%seguros", rating: 5, date: "2025-08-20" },
  ],
  "dream-league-soccer": [
    { author: "Eliezer Baena", content: "es confiable, al principio si tenía miedo porque la página se había quedado pegada cuando uno pulsa la opción de ir a WhatsApp, de ahí para adelante muy rápido todo, exelente servicio 💯", rating: 5, date: "2026-07-20" },
    { author: "Isanyermillan", content: "Al q este en busca de recargar dls o cualquier otra recalca hágalo sin ningún tipo de problema porque son muy seguros y muy buenas y al instante le doy muchísima recomendacion", rating: 5, date: "2026-05-16" },
    { author: "Melbin", content: "Gente les recomiendo este medio para recargar sus juegos.. Son personas responsables confiables totalmente seguro, se los recomiendo al 100% fue un proceso corto y seguro.", rating: 5, date: "2025-07-16" },
    { author: "jh548741", content: "Excelente servicio hermanos responden de inmediato te tienen paciencia 100% seguros   Así se trata a un cliente excelente  ✌️👌", rating: 5, date: "2025-09-06" },
    { author: "Martin", content: "Quedé muy satisfecho con el servicio muy fácil los que te atienden te explican bien... La verdad muy seguro, lo recomiendo", rating: 5, date: "2025-08-17" },
    { author: "Germán", content: "Me encantó de verdad cien por ciento seguro y lo más importante es totalmente seguro lo recomiendo mucho", rating: 5, date: "2025-07-16" },
    { author: "Jesús", content: "Excelente servicio, la verdad son muy confiable y muy fácil de recargar. Bendiciones", rating: 5, date: "2025-07-23" },
    { author: "Hiann", content: "Fue una exelente servicio estaré recargando por aquí múltiples juegos muchas gracias", rating: 5, date: "2025-11-08" },
    { author: "sanchez22944", content: "Rápido , seguro y repuestas rápida a cada uno de sus perdido ,lo mejor de lo mejor", rating: 5, date: "2025-12-21" },
    { author: "maria meza", content: "Excelente servicio,de verdad lo recomiendo al 💯 son muy y buenos y rápidos 🖖", rating: 5, date: "2026-07-25" },
    { author: "Juan Carlos", content: "Excelente servicio si quieren recargar les recomiendo esta página muy buena", rating: 5, date: "2026-06-13" },
    { author: "Emanuel Montoya", content: "Me encantó de verdad cien por cientos muy recomendable es totalmente re", rating: 5, date: "2026-07-12" },
    { author: "navasyoiner9", content: "Excelente centro de recarga mi valoracion es perfecta y muy confiable", rating: 5, date: "2026-04-15" },
    { author: "Ramny", content: "Excelente servicio hermano es confiable se los recomiendo al 100%", rating: 5, date: "2025-09-13" },
    { author: "maria meza", content: "Excelente muy rápidas las recargas,es seguro y excelente atención", rating: 5, date: "2026-07-12" },
    { author: "Juan Coronel", content: "Un servicio muy bueno y personas muy amables lo recomiendo mucho", rating: 5, date: "2026-07-09" },
    { author: "Jesus", content: "Excelente servicio, muy confiables, 100% seguro y recomendado", rating: 5, date: "2026-02-16" },
    { author: "Jose", content: "Muy confiable recomendado al 100 gracias respuesta inmediata", rating: 5, date: "2026-01-07" },
  ],
  "efootball": [
    { author: "Daniel", content: "Súper confiable yo también cuando fui a recargar leía los comentarios y decía y si esos comentarios los hizo el mismo jajaja pero no súper confiable la página", rating: 5, date: "2026-07-19" },
    { author: "Diego", content: "Hola para cualquiera que quiera recargar yo lo recomiendo al 100% yo también tenía mis dudas pero ya las dejé de tener un servicio excelente 5 estrellas", rating: 5, date: "2026-04-17" },
    { author: "Juan", content: "Gordo de verdad un millón de profesionalismo de verdad que hacen las cosas bien la recomiendo un millón en 10 minutos o menos hicieron su trabajo", rating: 5, date: "2025-09-06" },
    { author: "Jhonathan", content: "Muy rápida de verdad quedo satisfecho, al principio con miedo por una estafa a pero no el trato fue bueno nos explicaron y todo 100% recomendado", rating: 5, date: "2025-11-01" },
    { author: "Angel", content: "Excelente servicio. Era mi primera vez y me dió miedo Pero son muy responsables y muy atentos no duraron ni 15 minutos haciendo el proceso.", rating: 5, date: "2025-07-29" },
    { author: "Jonatan Pérez", content: "Con el miedo del mundo lo hice, pero 100% recomendado. Todo muy bien y no hacen lo que muchos piensan es que es robar. Se los recomiendo.", rating: 5, date: "2025-11-19" },
    { author: "Alejandro frade", content: "Excelente son muy confiables, compren sin desconfianza, excelente servicio, y es bueno porque podemos pagar por pago móvil tranquilamente", rating: 5, date: "2026-03-16" },
    { author: "Salvador", content: "Los mejores de verdad te después de la recarga ya lista tambiem te ayudan a como ingresar de verdad les recomiendo si son de confianza", rating: 5, date: "2026-06-17" },
    { author: "Idairo añez", content: "Muy buena está plata forma para recargar es 100% confiable hice la recarga dudando Pero si me hicieron la recarga se las recomiendo", rating: 5, date: "2026-06-10" },
    { author: "Anthony", content: "los mejores, duré mucho tiempo buscando alguien q realizará recargas y ellos han sido mi solución, excelente servicio y atención", rating: 5, date: "2026-03-20" },
    { author: "Gabriel Palacios", content: "Excelente al principio no confiaba, pero no tardaron en responder y todo funcionó con éxito todo muy rápido y fácil de entender", rating: 5, date: "2026-06-09" },
    { author: "Carlos", content: "Muy buena atención lo hise con mucho miedo por q era nuevo en esto de las recargas pero si es verdad no te roban como piensas", rating: 5, date: "2026-03-02" },
    { author: "Gabriel Palacios", content: "Excelente al precio no confiaba, pero no tardaron en responder y todo funcionó con éxito todo muy rápido y fácil de entender", rating: 5, date: "2026-06-09" },
    { author: "Jesus", content: "Lo mejor super confiable 100% pensé que era estafa pero ayudan mucho ya que uno no tiene una cuánta bancaria del exterior", rating: 5, date: "2026-07-20" },
    { author: "alejandromana664", content: "La recomiendo a full🤩 al principio andaba asustado, luego vi que era 100% real, Recarguen con pitanga, confianza total", rating: 5, date: "2026-01-10" },
    { author: "Anthony", content: "duré mucho tiempo buscando alguien q realizará recargas y ellos han sido mi solución, excelente servicio y atención", rating: 5, date: "2026-03-20" },
    { author: "juan", content: "aunque genere dudas es un excelente servicio, me atendieron de manera inmediata ya tengo mis recargas de confianza", rating: 5, date: "2026-07-30" },
    { author: "Gabriel Peroza", content: "al principio tuve miedo, pero 100% recomendados, hacen efectiva la recarga rápido y trabajan de manera perfecta", rating: 5, date: "2025-12-03" },
  ],
  "roblox": [
    { author: "Lázaro", content: "Es exelente si estás en Venezuela. Yo pensé que era una estafa pero el servicio es bueno, te llega rápido la recarga y además la facilidad de pagar en BS es buena para los que no cuentan con facilidad de tarjeta de crédito. 100% recomendado", rating: 5, date: "2025-10-09" },
    { author: "Angel", content: "Está es una exelente página para hacer sus recargas de sus juegos favoritos son muy atentos y el servicio es rápido y facil de aprender a usar no se tardan nada es realizar los pedidos los recomiendo 10/10", rating: 5, date: "2025-08-25" },
    { author: "Bradt Gmail", content: "Excelente servicio demasiado legal y confiable solo tiene que demorar un poco de tiempo pero el tiempo vale la pena muy buen servicio estoy convencido está es la mejor pagina web legal de robux", rating: 5, date: "2026-06-29" },
    { author: "Manuel", content: "Es un excelente servicio y no se compara con otro sitio ni servicio de recargas, ellos son los mejores y son muy rápidos a la hora de atenderte se los recomiendo mucho mi gente", rating: 5, date: "2026-02-23" },
    { author: "Jhosttyn", content: "La verdad al principio tenía miedo porque como es una página pero el servicio fue rápido y estaba jugando mientras me hicieron la recarga muy bien la verdad", rating: 5, date: "2025-12-17" },
    { author: "Alejandro", content: "Es un buen servicio, me equivoqué 3 veces y no perdió la paciencia, de verdad les recomiendo recargar para su juego preferido, es un muy buen servicio", rating: 5, date: "2025-09-13" },
    { author: "Daniel", content: "Fue un poco lenta al realizar el procedimiento pero es confiable y eficaz tuve dudas por la demora pero si son confiables, la verdad la recomiendo:)", rating: 4, date: "2026-05-01" },
    { author: "Jesús chiriquez", content: "Me gusta este sitio de recargas sin duda seguiré haciendo recargas aquí,en las recargas no hay que esperar mucho 100% confíen en esta página", rating: 5, date: "2025-10-31" },
    { author: "mrromero117", content: "10/10. Compre antes de la hora de apertura y a la hora me escribieron y me pidieron los datos y al instante se efectuo la recarga.", rating: 5, date: "2025-10-03" },
    { author: "Beiker", content: "Muy excelente servicio, se los recomiendo, son rápidos haciendo su trabajo y tiene diferentes formas de pago accesibles.", rating: 5, date: "2025-09-20" },
    { author: "Diego", content: "Muy buen servicio demasiado confiables y la recargar fue demasiado rápido ni 5 minutos se tardaron la recomiendo al 100%", rating: 5, date: "2025-09-28" },
    { author: "Adrian Ruiz", content: "Le doy un dos porque quería recargar el ma madrugada y no estaban disponible que mal pero es confiable se los recomiendo", rating: 3, date: "2025-10-03" },
    { author: "32DemVil", content: "Pensé que iba a ser un dolor de cabeza como en otras páginas, pero ellos me demostraron que no, de verdad son confiables", rating: 5, date: "2026-01-08" },
    { author: "cesartapias50", content: "Excelente servicio, son rápidos en cuanto comprueban el pago, a pesar de la hora atienden y realizan la compra rápido", rating: 5, date: "2025-09-20" },
    { author: "Charlie", content: "Súper confiables, y toca recalcar que tienen una paciencia inmensa ya que me equivoqué cuatro veces con mis datos lol", rating: 5, date: "2026-04-17" },
    { author: "Andrés", content: "Muy buena aplicación te atienden bien la recarga no dura ni 5 minutos y lo tienes al instante la recomiendo mucho", rating: 5, date: "2025-08-31" },
    { author: "Steban", content: "Muy buena atención al cliente y las recargas son al instante me gusta lo rápido que son al realizar las recargas", rating: 5, date: "2026-05-13" },
    { author: "Aaron", content: "Muy recomendado sin duda, excelente servido y sinceridad, muy buenos precios. Lo recomiendo para todos, no teman", rating: 5, date: "2026-07-05" },
  ],
  "clash-royale": [
    { author: "Handiel", content: "Se las recomiendo muy confiable no duden en recargar en esta plataforma", rating: 5, date: "2026-06-02" },
    { author: "Gerardo", content: "La verdad el servicio muy rápido y muy bueno, se los recomiendo full", rating: 5, date: "2025-08-24" },
    { author: "Josmar", content: "Muy buena pagina la verdad, es muy confiable y rápida", rating: 5, date: "2026-05-07" },
    { author: "George Assaf", content: "todo perfecto", rating: 5, date: "2026-01-14" },
  ],
  "fortnite": [
    { author: "Andres parra", content: "100% confiables, excelente servicio te atienden de una vez no tardan ni 10 minutos, los recomiendo", rating: 5, date: "2025-09-02" },
    { author: "Rafael", content: "Excelente servicio, muy responsables y rápidos en todo el proceso", rating: 5, date: "2026-06-06" },
    { author: "Nacho", content: "Super recomendado, te hacen todo en menos de 10 minutos", rating: 5, date: "2025-11-09" },
    { author: "Juan", content: "Exelente servicio, fue muy rápido súper recomendado", rating: 5, date: "2026-07-26" },
    { author: "paolavelasco2926", content: "Excelente la atención muy rápida 10% recomendado", rating: 5, date: "2025-09-27" },
  ],
  "wild-rift": [
    { author: "Aaron", content: "Muy buena la atención al cliente, si pasa algo ellos te responden al instante así que todo muy perfecto la atención excelente", rating: 5, date: "2026-03-14" },
    { author: "leonardo33741", content: "De las experiencias más rápidas a la hora de recargar y tienen una muy buena atención al cliente", rating: 5, date: "2025-11-29" },
    { author: "Cristian", content: "Bastante rápido me parece excelente el servicio que brinda esta página, agradecido", rating: 5, date: "2025-12-22" },
    { author: "Andrés", content: "Súper rápidos y confiables a la hora de realizar la recarga y lo mejor a Bs", rating: 5, date: "2025-09-18" },
    { author: "Luis arenas", content: "Es muy bien servicio lo recomiendo con los ojos cerrados", rating: 5, date: "2025-12-27" },
    { author: "Etna", content: "Me gustó mucho es confiable vale la pena", rating: 5, date: "2026-01-08" },
    { author: "Dheyker", content: "Probando por primera vez", rating: 5, date: "2026-01-10" },
  ],
  "brawl-stars": [
    { author: "alejandro.smr777", content: "En verdad siempre tuve desconfianza de sitios así, pero me animé y lo hice, el proceso es igual de fácil que como lo muestran, como se ve de fácil, fácil se ve, ningún tipo de inconveniente ❤️", rating: 5, date: "2026-07-05" },
    { author: "Manuucrbl", content: "excelente servicio, rápido y confiables, 100% recomendados para cualquier servicio, si están dudando en trabajar con ellos, pierdan esa duda porque son 1000% confiables", rating: 5, date: "2026-07-08" },
    { author: "Yeifer", content: "Muy pero muy buen servicio, mi pedido llego en menos de 10 minutos, lo recomiendo muchísimo es 100% confiable", rating: 5, date: "2026-07-11" },
  ],
  "clash-of-clans": [
    { author: "Amy", content: "Excelente servicio, recarga rápido y son confiables.", rating: 5, date: "2026-07-09" },
    { author: "Jeison", content: "Es exelente", rating: 5, date: "2026-07-14" },
    { author: "Jeison", content: "Es bueno", rating: 5, date: "2026-07-14" },
  ],
};

export function getReviewsForSlug(slug: string): ProductReview[] {
  return reviewsBySlug[slug] ?? [];
}

export function getAverageRating(slug: string): { average: number; count: number } {
  const reviews = getReviewsForSlug(slug);
  if (reviews.length === 0) return { average: 0, count: 0 };
  const sum = reviews.reduce((acc, r) => acc + r.rating, 0);
  return { average: Math.round((sum / reviews.length) * 10) / 10, count: reviews.length };
}